# Generated by Django 6.0.6 on 2026-07-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessment",
            name="graded_at",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="weighted_score",
        ),
        migrations.AlterField(
            model_name="module",
            name="target_grade",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
