# Generated by Django 6.0.6 on 2026-07-30 15:01

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_remove_assessment_graded_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Not Started", "Not Started"),
                    ("In Progress", "In Progress"),
                    ("Submitted", "Submitted"),
                    ("Graded", "Graded"),
                ],
                default="Not Started",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="target_grade",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.UniqueConstraint(
                fields=("semester", "module_code"),
                name="unique_module_code_per_semester",
            ),
        ),
        migrations.AddConstraint(
            model_name="semester",
            constraint=models.UniqueConstraint(
                fields=("user", "name", "academic_year"),
                name="unique_semester_per_user",
            ),
        ),
    ]
