# Generated by Django 6.0.6 on 2026-08-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academics",
            "0003_alter_assessment_status_alter_module_target_grade_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="effort_level",
            field=models.CharField(
                choices=[("Low", "Low"), ("Medium", "Medium"), ("High", "High")],
                default="Medium",
                max_length=10,
            ),
        ),
    ]
