# Generated by Django 6.0.6 on 2026-08-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_assessment_effort_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="maximum_score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
