# Generated by Django 6.0.6 on 2026-08-25 15:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_alter_assessment_maximum_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="maximum_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("100.00"),
                max_digits=6,
                null=True,
            ),
        ),
    ]
